os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="sfml/2.4.1"
    - CONAN_USERNAME="GatorQue"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1

addons:
  apt:
    packages:
    - freeglut3-dev
    - git
    - cmake
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libglew-dev
    - libjpeg-dev
    - libopenal-dev
    - libpthread-stubs0-dev
    - libsndfile1-dev
    - libssl-dev # For conan package manager
    - libudev-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxcb-image0-dev
    - libxrandr-dev
    - udev

#cache:
#  apt: true

#matrix:
#   include:
#       - os: osx
#         osx_image: xcode8 # apple-clang 8.0
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode7.3 # apple-clang 7.3
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode7.1 # apple-clang 7.0
#         language: generic
#         env:
#       - os: osx
#         osx_image: xcode6.4 # apple-clang 6.1
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode6.2 # apple-clang 6.0
#         language: generic
#         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
