os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="sfml/2.4.1"
    - CONAN_USERNAME="GatorQue"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
#    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
#    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 
#    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
#    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
#    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
#    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1

#addons:
#  apt:
#    packages:
#    - freeglut3-dev
#    - git
#    - cmake                 # For SFML
#    - libfreetype6-dev      # For SFML
#    - libgl1-mesa-dev       # For SFML
#    - libglew-dev           # For SFML
#    - libgpgme11-dev        # For SFML
#    - libjpeg8-dev          # For SFML
#    - libjpeg62             # For SFML
#    - libopenal-dev         # For SFML
#    - libpthread-stubs0-dev # For SFML
#    - libsndfile1-dev       # For SFML
#    - libssl-dev            # For Conan
#    - libudev-dev           # For SFML
#    - libx11-dev            # For SFML
#    - libx11-xcb-dev        # For SFML
#    - libxcb-randr0-dev     # For SFML
#    - libxcb-image0-dev     # For SFML
#    - libxrandr-dev         # For SFML

#cache:
#  apt: true

#matrix:
#   include:
#       - os: osx
#         osx_image: xcode8 # apple-clang 8.0
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode7.3 # apple-clang 7.3
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode7.1 # apple-clang 7.0
#         language: generic
#         env:
#       - os: osx
#         osx_image: xcode6.4 # apple-clang 6.1
#         language: generic
#         env:
#       - os: osx 
#         osx_image: xcode6.2 # apple-clang 6.0
#         language: generic
#         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
